/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package SistemaInternacionGUI;

import SistemaInternacionConexion.Conexion;

/**
 *
 * @author Franco
 */
public class sistemaInternacionGUI extends javax.swing.JFrame {

    /**
     * Creates new form sistemaInternacionGUI
     */
    public sistemaInternacionGUI() {
        initComponents();
        this.setLocationRelativeTo(null);
        
   
        Conexion objetoconexion = new Conexion();
        objetoconexion.establecerConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jbUbicacion = new javax.swing.JButton();
        jbHabitacion = new javax.swing.JButton();
        jbCama = new javax.swing.JButton();
        jbInternacion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbUbicacion.setText("Ubicacion");
        jbUbicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbUbicacionActionPerformed(evt);
            }
        });

        jbHabitacion.setText("Habitacion");
        jbHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbHabitacionActionPerformed(evt);
            }
        });

        jbCama.setText("Cama");
        jbCama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCamaActionPerformed(evt);
            }
        });

        jbInternacion.setText("Internacion");
        jbInternacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInternacionActionPerformed(evt);
            }
        });

        jLabel1.setText("Sistema de internacion");

        jLabel2.setText("Seleccione la opcion que desea realizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbUbicacion)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbHabitacion)
                                .addGap(18, 18, 18)
                                .addComponent(jbCama))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbInternacion)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel2)
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbUbicacion)
                    .addComponent(jbHabitacion)
                    .addComponent(jbCama)
                    .addComponent(jbInternacion))
                .addContainerGap(158, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbUbicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbUbicacionActionPerformed
        Ubicacionui ubicacion = new Ubicacionui();
        ubicacion.setVisible(true);
    }//GEN-LAST:event_jbUbicacionActionPerformed

    private void jbHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbHabitacionActionPerformed
         Habitacionui habitacion = new Habitacionui();
         habitacion.setVisible(true);
    }//GEN-LAST:event_jbHabitacionActionPerformed

    private void jbCamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCamaActionPerformed
         Camaui cama = new Camaui();
        cama.setVisible(true);
    }//GEN-LAST:event_jbCamaActionPerformed

    private void jbInternacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInternacionActionPerformed
       Internacionui internacion = new Internacionui();
       internacion.setVisible(true);
    }//GEN-LAST:event_jbInternacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(sistemaInternacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(sistemaInternacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(sistemaInternacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(sistemaInternacionGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new sistemaInternacionGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jbCama;
    private javax.swing.JButton jbHabitacion;
    private javax.swing.JButton jbInternacion;
    private javax.swing.JButton jbUbicacion;
    // End of variables declaration//GEN-END:variables
}
